---

- name: has {{ traefik_service_name }} config directory
  file:
    path: "{{ traefik_host_config_dir }}/conf"
    state: "directory"
    mode: "0775"

- name: has {{ traefik_service_name }} configuration on host
  template:
    src: docker-traefik.toml.j2
    dest: "{{ traefik_host_config_dir }}/conf/traefik.toml"
    mode: "0664"
    backup: yes
  notify: traefik restart

- name: has {{ traefik_service_name }} service config on host
  become: true
  template:
    src: docker-traefik.service.j2
    dest: "/etc/systemd/system/{{ traefik_service_name }}.service"
    backup: yes
  notify: traefik restart