---
- name: "has stopped {{ traefik_service_name }} service"
  become: true
  service:
    name: "{{ service.traefik_service_name }}"
    enabled: no
    state: stopped
  ignore_errors: yes

- name: "has not {{ traefik_host_config_dir }} directory on host"
  become: true
  file:
    path: "{{ traefik_host_config_dir }}"
    state: absent

- name: "has not /etc/systemd/system/{{ traefik_service_name }}.service on host"
  become: true
  file:
    path: "/etc/systemd/system/{{ traefik_service_name }}.service"
    state: absent
  notify: reload systemctl daemon
